<?php

namespace HG\ImageRepositoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HGImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HGImageRepository extends EntityRepository
{
  public function getMaxId()
  {
    return $this->createQueryBuilder('i')
    ->select('MAX(i.img_id)')
    ->getQuery()
    ->getSingleScalarResult();
  }
}
